# Generated by Django 3.2.25 on 2024-03-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=10)),
                ('notes', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('phone_no', models.IntegerField(null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_date', models.DateField()),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_date', models.DateField()),
                ('status', models.IntegerField(default=1)),
                ('user', models.ManyToManyField(to='User.Role')),
            ],
        ),
    ]
