# Generated by Django 3.2.25 on 2024-03-13 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='User.user')),
                ('role', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='User.role')),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
