# Generated by Django 3.2.25 on 2024-03-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_userrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='role_data',
        ),
    ]
