# Generated by Django 3.2.25 on 2024-03-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start',
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('project', models.ManyToManyField(to='Project.Project')),
            ],
        ),
    ]
